Repository Talljack/vscode-auto-space, pull requests merged in 2023-10, with the labels that each got.

#18 Update README.md
  README.md
Labels: size/XS

#14 Update utils.ts
  src/utils.ts
Labels: size/S

#19 fix: optimize regexp
  src/utils.ts
Labels: size/XS

#20 fix: use pangu to add space
  package.json
  pnpm-lock.yaml
  src/index.ts
  src/utils.ts
Labels: size/L

#21 fix: use pangu to add space
  src/index.ts
  src/utils.ts
Labels: size/S
